Fixed GPG setup

diff --git a/pacman/work b/pacman/work
--- a/pacman/work
+++ b/pacman/work
@@ -3,21 +3,23 @@
 setup bw
 setup tools
 
+install yubikey-manager
+sudo systemctl start pcscd.service
+sudo systemctl enable pcscd.service
+gpg --card-status || (echo "Cannot detect Yubikey" && exit 1)
+
 mkdir -p ~/.ssh
 bw get item "fb21d443-4f27-4812-a404-aca401096867" | jq -r ".notes" | gpg --import
-echo "5\ny\n" | gpg --command-fd 0 --expert --edit-key 0E5F27342AF9AFB6FCE9504635AB7E86500DD327 trust
+echo "0E5F27342AF9AFB6FCE9504635AB7E86500DD327:6" | gpg --import-ownertrust
 gpg --export-ssh-key gga@kialo.com > ~/.ssh/id_card.pub
 chmod 0600 ~/.ssh/id_card.pub
 echo "enable-ssh-support" > ~/.gnupg/gpg-agent.conf
 get assets/zsh/gpg.zsh ~/.config/zsh/gpg.zsh
 echo ". ~/.config/zsh/gpg.zsh" >> ~/.zshrc
-grep 'Host kialo' ~/.ssh/config || cat << EOF >> ~/.ssh/config
+touch ~/.ssh/config
+grep 'Host kialo' ~/.ssh/config > /dev/null 2>&1 || cat << EOF >> ~/.ssh/config
 Host kialo
   Hostname github.com
   IdentityFile ~/.ssh/id_card.pub
   IdentitiesOnly yes
 EOF
-
-install yubikey-manager
-sudo systemctl start pcscd.service
-sudo systemctl enable pcscd.service
